apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bookinfo
  namespace: argocd
spec:
  generators:
    - clusters:
            selector:
              matchLabels:
                use: prod

  template:
    metadata:
      name: '{{name}}-bookinfo'
        
    spec:
      project: default
      source:
        repoURL: https://github.com/sawyer523/geektime-devops.git
        targetRevision: HEAD
        path: week14/bookinfo
      destination:
        server: '{{server}}'  # Secret 的 'server' 字段
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
